services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-course-app
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: student_course_app
      DB_USERNAME: laravel_user
      DB_PASSWORD: StrongPassword123

  mysql:
    image: mysql:8.0
    container_name: student-course-mysql
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: student_course_app
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: StrongPassword123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: